// DO NOT EDIT MANUALLY
export const LANGUAGES = [
  "abap",
  "abnf",
  "actionscript",
  "ada",
  "agda",
  "al",
  "antlr4",
  "apacheconf",
  "apex",
  "apl",
  "applescript",
  "aql",
  "arduino",
  "arff",
  "armasm",
  "arturo",
  "asciidoc",
  "asm6502",
  "asmatmel",
  "aspnet",
  "autohotkey",
  "autoit",
  "avisynth",
  "avro-idl",
  "awk",
  "bash",
  "basic",
  "batch",
  "bbcode",
  "bbj",
  "bicep",
  "birb",
  "bison",
  "bnf",
  "bqn",
  "brainfuck",
  "brightscript",
  "bro",
  "bsl",
  "c",
  "cfscript",
  "chaiscript",
  "cil",
  "cilkc",
  "cilkcpp",
  "clike",
  "clojure",
  "cmake",
  "cobol",
  "coffeescript",
  "concurnas",
  "cooklang",
  "coq",
  "cpp",
  "crystal",
  "csharp",
  "cshtml",
  "csp",
  "css-extras",
  "css",
  "csv",
  "cue",
  "cypher",
  "d",
  "dart",
  "dataweave",
  "dax",
  "dhall",
  "diff",
  "django",
  "dns-zone-file",
  "docker",
  "dot",
  "ebnf",
  "editorconfig",
  "eiffel",
  "ejs",
  "elixir",
  "elm",
  "erb",
  "erlang",
  "etlua",
  "excel-formula",
  "factor",
  "false",
  "firestore-security-rules",
  "flow",
  "fortran",
  "fsharp",
  "ftl",
  "gap",
  "gcode",
  "gdscript",
  "gedcom",
  "gettext",
  "gherkin",
  "git",
  "glsl",
  "gml",
  "gn",
  "go-module",
  "go",
  "gradle",
  "graphql",
  "groovy",
  "haml",
  "handlebars",
  "haskell",
  "haxe",
  "hcl",
  "hlsl",
  "hoon",
  "hpkp",
  "hsts",
  "http",
  "ichigojam",
  "icon",
  "icu-message-format",
  "idris",
  "iecst",
  "ignore",
  "inform7",
  "ini",
  "io",
  "j",
  "java",
  "javadoc",
  "javadoclike",
  "javascript",
  "javastacktrace",
  "jexl",
  "jolie",
  "jq",
  "js-extras",
  "js-templates",
  "jsdoc",
  "json",
  "json5",
  "jsonp",
  "jsstacktrace",
  "jsx",
  "julia",
  "keepalived",
  "keyman",
  "kotlin",
  "kumir",
  "kusto",
  "latex",
  "latte",
  "less",
  "lilypond",
  "linker-script",
  "liquid",
  "lisp",
  "livescript",
  "llvm",
  "log",
  "lolcode",
  "lua",
  "magma",
  "makefile",
  "markdown",
  "markup-templating",
  "markup",
  "mata",
  "matlab",
  "maxscript",
  "mel",
  "mermaid",
  "metafont",
  "mizar",
  "mongodb",
  "monkey",
  "moonscript",
  "n1ql",
  "n4js",
  "nand2tetris-hdl",
  "naniscript",
  "nasm",
  "neon",
  "nevod",
  "nginx",
  "nim",
  "nix",
  "nsis",
  "objectivec",
  "ocaml",
  "odin",
  "opencl",
  "openqasm",
  "oz",
  "parigp",
  "parser",
  "pascal",
  "pascaligo",
  "pcaxis",
  "peoplecode",
  "perl",
  "php-extras",
  "php",
  "phpdoc",
  "plant-uml",
  "plsql",
  "powerquery",
  "powershell",
  "processing",
  "prolog",
  "promql",
  "properties",
  "protobuf",
  "psl",
  "pug",
  "puppet",
  "pure",
  "purebasic",
  "purescript",
  "python",
  "q",
  "qml",
  "qore",
  "qsharp",
  "r",
  "racket",
  "reason",
  "regex",
  "rego",
  "renpy",
  "rescript",
  "rest",
  "rip",
  "roboconf",
  "robotframework",
  "ruby",
  "rust",
  "sas",
  "sass",
  "scala",
  "scheme",
  "scss",
  "shell-session",
  "smali",
  "smalltalk",
  "smarty",
  "sml",
  "solidity",
  "solution-file",
  "soy",
  "sparql",
  "splunk-spl",
  "sqf",
  "sql",
  "squirrel",
  "stan",
  "stata",
  "stylus",
  "supercollider",
  "swift",
  "systemd",
  "t4-cs",
  "t4-templating",
  "t4-vb",
  "tap",
  "tcl",
  "textile",
  "toml",
  "tremor",
  "tsx",
  "tt2",
  "turtle",
  "twig",
  "typescript",
  "typoscript",
  "unrealscript",
  "uorazor",
  "uri",
  "v",
  "vala",
  "vbnet",
  "velocity",
  "verilog",
  "vhdl",
  "vim",
  "visual-basic",
  "warpscript",
  "wasm",
  "web-idl",
  "wgsl",
  "wiki",
  "wolfram",
  "wren",
  "xeora",
  "xml-doc",
  "xojo",
  "xquery",
  "yaml",
  "yang",
  "zig",
] as const;
export const PLUGINS = [
  "autolinker",
  "autoloader",
  "command-line",
  "copy-to-clipboard",
  "custom-class",
  "data-uri-highlight",
  "diff-highlight",
  "download-button",
  "file-highlight",
  "filter-highlight-all",
  "highlight-keywords",
  "inline-color",
  "jsonp-highlight",
  "keep-markup",
  "line-highlight",
  "line-numbers",
  "match-braces",
  "normalize-whitespace",
  "previewers",
  "remove-initial-line-feed",
  "show-invisibles",
  "show-language",
  "toolbar",
  "treeview",
  "unescaped-markup",
  "wpd",
] as const;
export const LANGUAGE_DEPENDENCIES: Partial<
  Record<(typeof LANGUAGES)[number], (typeof LANGUAGES)[number][]>
> = {
  javascript: ["clike"],
  actionscript: ["javascript"],
  apex: ["clike", "sql"],
  arduino: ["cpp"],
  aspnet: ["markup", "csharp"],
  birb: ["clike"],
  bison: ["c"],
  c: ["clike"],
  csharp: ["clike"],
  cpp: ["c"],
  cfscript: ["clike"],
  chaiscript: ["clike", "cpp"],
  cilkc: ["c"],
  cilkcpp: ["cpp"],
  coffeescript: ["javascript"],
  crystal: ["ruby"],
  "css-extras": ["css"],
  d: ["clike"],
  dart: ["clike"],
  django: ["markup-templating"],
  ejs: ["javascript", "markup-templating"],
  etlua: ["lua", "markup-templating"],
  erb: ["ruby", "markup-templating"],
  fsharp: ["clike"],
  "firestore-security-rules": ["clike"],
  flow: ["javascript"],
  ftl: ["markup-templating"],
  gml: ["clike"],
  glsl: ["c"],
  go: ["clike"],
  gradle: ["clike"],
  groovy: ["clike"],
  haml: ["ruby"],
  handlebars: ["markup-templating"],
  haxe: ["clike"],
  hlsl: ["c"],
  idris: ["haskell"],
  java: ["clike"],
  javadoc: ["markup", "java", "javadoclike"],
  jolie: ["clike"],
  jsdoc: ["javascript", "javadoclike", "typescript"],
  "js-extras": ["javascript"],
  json5: ["json"],
  jsonp: ["json"],
  "js-templates": ["javascript"],
  kotlin: ["clike"],
  latte: ["clike", "markup-templating", "php"],
  less: ["css"],
  lilypond: ["scheme"],
  liquid: ["markup-templating"],
  markdown: ["markup"],
  "markup-templating": ["markup"],
  mongodb: ["javascript"],
  n4js: ["javascript"],
  objectivec: ["c"],
  opencl: ["c"],
  parser: ["markup"],
  php: ["markup-templating"],
  phpdoc: ["php", "javadoclike"],
  "php-extras": ["php"],
  plsql: ["sql"],
  processing: ["clike"],
  protobuf: ["clike"],
  pug: ["markup", "javascript"],
  purebasic: ["clike"],
  purescript: ["haskell"],
  qsharp: ["clike"],
  qml: ["javascript"],
  qore: ["clike"],
  racket: ["scheme"],
  cshtml: ["markup", "csharp"],
  jsx: ["markup", "javascript"],
  tsx: ["jsx", "typescript"],
  reason: ["clike"],
  ruby: ["clike"],
  sass: ["css"],
  scss: ["css"],
  scala: ["java"],
  "shell-session": ["bash"],
  smarty: ["markup-templating"],
  solidity: ["clike"],
  soy: ["markup-templating"],
  sparql: ["turtle"],
  sqf: ["clike"],
  squirrel: ["clike"],
  stata: ["mata", "java", "python"],
  "t4-cs": ["t4-templating", "csharp"],
  "t4-vb": ["t4-templating", "vbnet"],
  tap: ["yaml"],
  tt2: ["clike", "markup-templating"],
  textile: ["markup"],
  twig: ["markup-templating"],
  typescript: ["javascript"],
  v: ["clike"],
  vala: ["clike"],
  vbnet: ["basic"],
  velocity: ["markup"],
  wiki: ["markup"],
  xeora: ["markup"],
  "xml-doc": ["markup"],
  xquery: ["markup"],
};
